# Configuration Sonata Pages
sonata_page:
    multisite: host
    use_streamed_response: true # set the value to false in debug mode or if the reverse proxy does not handle streamed response
    ignore_route_patterns:
        - ^(.*)admin(.*)   # ignore admin route, ie route containing 'admin'
        - ^_(.*)          # ignore symfony routes
    ignore_routes:
        - sonata_page_esi_cache
        - sonata_page_ssi_cache
        - sonata_page_js_sync_cache
        - sonata_page_js_async_cache
        - sonata_cache_esi
        - sonata_cache_ssi
        - sonata_cache_js_async
        - sonata_cache_js_sync
        - sonata_cache_apc

    ignore_uri_patterns:
        - ^/admin(.*)   # ignore admin route, ie route containing 'admin'

    page_defaults:
        homepage: {decorate: false} # disable decoration for homepage, key - is a page route
    default_template: default # template key from templates section, used as default for pages
    templates:
        default:
            path: 'InfoMiageAppBundle::layout.html.twig'
            name: Defaut
            containers:
                 header:
                     name: Header
                 content_top:
                     name: Top content
                 content:
                     name: Contenu principal
                 content_bottom:
                     name: Bottom content
                 footer:
                     name: Footer
            matrix:
                 layout: |
                 
                     HHHHHHHH
                     TTTTBBBB
                     TTTTBBBB
                     TTTTBBBB
                     TTTTBBBB
                     CCCCCCCC
                     CCCCCCCC
                     FFFFFFFF
                     
                 mapping:
                     H: header
                     T: content_top
                     C: content
                     B: content_bottom
                     F: footer
                     
    assets:
        stylesheets:
            - bundles/infomiageapp/css/bootstrap.min.css
            - bundles/infomiageapp/css/modern-business.css
            - bundles/infomiageapp/font-awesome/css/font-awesome.min.css
            - bundles/infomiageapp/css/style.css

        javascripts:
            - bundles/sonataadmin/vendor/jquery/dist/jquery.js
            - bundles/infomiageapp/js/bootstrap.min.js
            - bundles/sonatacore/js/base.js
            - bundles/sonatacore/vendor/select2/select2.min.js
            
        
    # manage the http errors
    catch_exceptions:
        not_found: [404]    # render 404 page with "not_found" key (name generated: _page_internal_error_{key})
        fatal:     [500]    # so you can use the same page for different http errors or specify specific page for each error
