# Configuration Sonata Seo
sonata_seo:
    encoding:         UTF-8
    page:
        default: sonata.seo.page.default
        title:            InfoMiage
        metas:
            name:
                keywords:             miage, evry, miagiste, diplome, ecole, fac
                description:          Site d'information sur la MIAGE
                robots:               index, follow

            property:
                # Facebook application settings
                #'fb:app_id':          XXXXXX
                #'fb:admins':          admin1, admin2

                # Open Graph information
                # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
                'og:site_name':       InfoMiage
                'og:description':     Site d'informations autour de la MIAGE

            http-equiv:
                'Content-Type':         text/html; charset=utf-8
                #'X-Ua-Compatible':      IE=EmulateIE7

        head:
            'xmlns':              http://www.w3.org/1999/xhtml
            'xmlns:og':           http://opengraphprotocol.org/schema/
            #'xmlns:fb':           "http://www.facebook.com/2008/fbml"